name: messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.5
  supabase_flutter: ^1.6.2
  flutter_svg: ^1.0.3
  chat_bubbles: ^1.5.0
  intl: ^0.18.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
  - family: 'Inter'
    fonts:
      - asset: 'fonts/Inter/Inter-Black.ttf'
        weight: 900
      - asset: 'fonts/Inter/Inter-Bold.ttf'
        weight: 700
      - asset: 'fonts/Inter/Inter-ExtraBold.ttf'
        weight: 800
      - asset: 'fonts/Inter/Inter-ExtraLight.ttf'
        weight: 200
      - asset: 'fonts/Inter/Inter-Light.ttf'
        weight: 300
      - asset: 'fonts/Inter/Inter-Medium.ttf'
        weight: 500
      - asset: 'fonts/Inter/Inter-Regular.ttf'
      - asset: 'fonts/Inter/Inter-SemiBold.ttf'
        weight: 600
      - asset: 'fonts/Inter/Inter-Thin.ttf'
        weight: 100

  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
